language: ruby

cache: bundler

services:
  - postgresql

addons:
  postgresql: '9.4'
  firefox: latest-beta

before_install:
  - export GECKO_URL=$(curl --fail -s -L https://github.com/mozilla/geckodriver/releases/latest | egrep -o '/mozilla/geckodriver/releases/download/v[0-9\.]+/geckodriver-v[0-9\.]+-linux64.tar.gz')
  - echo $GECKO_URL
  - echo $GECKO_URL | wget --no-verbose --base=https://github.com/ -i - -O /tmp/geckodriver-latest.tar.gz
  - mkdir geckodriver
  - tar -xzf /tmp/geckodriver-latest.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

before_script:
  - bundle exec rake client:npm_install
  - bundle exec rake client:build_and_deploy
  - psql -c 'create database mykonote_test;' -U postgres

jobs:
  include:
    - stage: test
      name: Rubocop
      script: bundle exec rubocop -D
    - stage: test
      name: RSpec
      script: bundle exec rspec spec
